mindmap
  root((CataMesh))
    DataProduct
        Metadata
        Spec
            Resource
                ResourceDefinition
    Reconciliation
        Validate
        Plan
        Diff
        Apply
        Deploy
