stateDiagram-v2
    [*] --> yamlToDataProduct
    yamlToDataProduct : YAML to Data Product
    yamlToDataProduct --> validateDataProductSchema
    validateDataProductSchema: Validate Data Product Schema
    validateDataProductSchema --> validateResourceSchema
    validateResourceSchema: Validate Resources Schema
    validateResourceSchema --> validateBucketDefinitionSchema
    validateBucketDefinitionSchema: Validate Bucket Definition Schema
    validateBucketDefinitionSchema --> loadCurrentDataProductForDiff
    loadCurrentDataProductForDiff: Get Current DataProduct
    loadCurrentDataProductForDiff --> diffDataProductHandler
    diffDataProductHandler: Diff Data Product
