stateDiagram-v2
    [*] --> yamlToDataProduct
    yamlToDataProduct : YAML to Data Product
    yamlToDataProduct --> validateDataProductSchema
    validateDataProductSchema: Validate Data Product Schema
    validateDataProductSchema --> validateResourceSchema
    validateResourceSchema: Validate Resources Schema
    validateResourceSchema --> loadCurrentDataProductForDiff
    loadCurrentDataProductForDiff: Get Current DataProduct
    loadCurrentDataProductForDiff --> diffDataProductHandler
    diffDataProductHandler: Diff Data Product
    diffDataProductHandler --> planDataProduct
    planDataProduct: Plan Data Product
