stateDiagram-v2
    state data_product_action <<choice>>
    state definition_action <<choice>>

    [*] --> yaml_to_data_product
    yaml_to_data_product --> validate_data_product_schema
    validate_data_product_schema --> validate_resource_schema
    validate_resource_schema --> validate_bucket_definition_schema
    validate_bucket_definition_schema --> check_if_exist_data_product
    check_if_exist_data_product --> data_product_action
    data_product_action --> create_data_product: create
    create_data_product --> check_if_exist_resources
    data_product_action --> check_if_exist_resources: update/noop
    check_if_exist_resources --> create_resources
    create_resources --> check_resource_definition_versions
    check_resource_definition_versions --> definition_action
    definition_action --> create_resource_definitions: create versions
    create_resource_definitions --> [*]
    definition_action --> [*]: all versions exist
